<?php

namespace ContainerZq6Pli0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrinhoFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CarrinhoForm' shared autowired service.
     *
     * @return \App\Form\CarrinhoForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CarrinhoForm.php';

        return $container->privates['App\\Form\\CarrinhoForm'] = new \App\Form\CarrinhoForm();
    }
}
