<?php

namespace ContainerHyzKXun;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KA030c2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kA030c2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kA030c2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produto' => ['privates', '.errored..service_locator.kA030c2.App\\Entity\\Produto', NULL, 'Cannot autowire service ".service_locator.kA030c2": it references class "App\\Entity\\Produto" but no such service exists.'],
            'session' => ['privates', '.errored..service_locator.kA030c2.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator.kA030c2": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists.'],
        ], [
            'em' => '?',
            'produto' => 'App\\Entity\\Produto',
            'session' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
        ]);
    }
}
