<?php

namespace ContainerHyzKXun;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vy4hvIrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vy4hvIr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vy4hvIr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            's' => ['privates', '.errored..service_locator.Vy4hvIr.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator.Vy4hvIr": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists.'],
        ], [
            's' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
        ]);
    }
}
