<?php

namespace ContainerRn0QyWB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VXCM2V0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VXCM2V0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VXCM2V0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Controller::add_carrinho' => ['privates', '.service_locator.kA030c2', 'get_ServiceLocator_KA030c2Service', true],
            'App\\Controller\\Controller::carrinho' => ['privates', '.service_locator.dbFJ5zg', 'get_ServiceLocator_DbFJ5zgService', true],
            'App\\Controller\\Controller::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\Controller::remove_carrinho' => ['privates', '.service_locator.G59fUp5', 'get_ServiceLocator_G59fUp5Service', true],
            'App\\Controller\\Controller::signup' => ['privates', '.service_locator.l_KMMhu', 'get_ServiceLocator_LKMMhuService', true],
            'App\\Controller\\ProdutoController::criar_produto' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProdutoController::index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\Controller:add_carrinho' => ['privates', '.service_locator.kA030c2', 'get_ServiceLocator_KA030c2Service', true],
            'App\\Controller\\Controller:carrinho' => ['privates', '.service_locator.dbFJ5zg', 'get_ServiceLocator_DbFJ5zgService', true],
            'App\\Controller\\Controller:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\Controller:remove_carrinho' => ['privates', '.service_locator.G59fUp5', 'get_ServiceLocator_G59fUp5Service', true],
            'App\\Controller\\Controller:signup' => ['privates', '.service_locator.l_KMMhu', 'get_ServiceLocator_LKMMhuService', true],
            'App\\Controller\\ProdutoController:criar_produto' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProdutoController:index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\Controller::add_carrinho' => '?',
            'App\\Controller\\Controller::carrinho' => '?',
            'App\\Controller\\Controller::login' => '?',
            'App\\Controller\\Controller::remove_carrinho' => '?',
            'App\\Controller\\Controller::signup' => '?',
            'App\\Controller\\ProdutoController::criar_produto' => '?',
            'App\\Controller\\ProdutoController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Controller:add_carrinho' => '?',
            'App\\Controller\\Controller:carrinho' => '?',
            'App\\Controller\\Controller:login' => '?',
            'App\\Controller\\Controller:remove_carrinho' => '?',
            'App\\Controller\\Controller:signup' => '?',
            'App\\Controller\\ProdutoController:criar_produto' => '?',
            'App\\Controller\\ProdutoController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
