<?php

namespace ContainerRn0QyWB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G59fUp5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G59fUp5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G59fUp5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'produto' => ['privates', '.errored..service_locator.G59fUp5.App\\Entity\\Produto', NULL, 'Cannot autowire service ".service_locator.G59fUp5": it references class "App\\Entity\\Produto" but no such service exists.'],
        ], [
            'produto' => 'App\\Entity\\Produto',
        ]);
    }
}
