<?php

namespace ContainerRn0QyWB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduto2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kA030c2.App\Entity\Produto' shared service.
     *
     * @return \App\Entity\Produto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kA030c2": it references class "App\\Entity\\Produto" but no such service exists.');
    }
}
