<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZGhYCKE\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZGhYCKE/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZGhYCKE.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZGhYCKE\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZGhYCKE\App_KernelProdContainer([
    'container.build_hash' => 'ZGhYCKE',
    'container.build_id' => 'ebe9ea95',
    'container.build_time' => 1642947174,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZGhYCKE');
