controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\Controller::index

login:
    path: /login
    controller: App\Controller\Controller::login

signup:
    path: /registar
    controller: App\Controller\Controller::signup

logout:
    path: /logout
    methods: GET

produtos:
    path: /produtos
    controller: App\Controller\ProdutoController::index

add_produto:
    path: /produto/add
    controller: App\Controller\ProdutoController::add_produto

admin:
    path: /admin
    controller: App\Controller\AdminController::admin_index

carrinho:
    path: /carrinho
    controller: App\Controller\Controller::carrinho

add_carrinho:
    path: /carrinho/add/{id}
    controller: App\Controller\Controller::add_carrinho

remove_carrinho:
    path: /carrinho/remove/{id}
    controller: App\Controller\Controller::remove_carrinho

whereweare:
    path: /where-we-are
    controller: App\Controller\Controller::whereweare

whoweare:
    path: /who-we-are
    controller: App\Controller\Controller::whoweare

contactus:
    path: /contact-us
    controller: App\Controller\Controller::contactus
