controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\Controller::index

login:
    path: /login
    controller: App\Controller\Controller::login

signup:
    path: /registar
    controller: App\Controller\Controller::signup

logout:
    path: /logout
    methods: GET

produtos:
    path: /produtos
    controller: App\Controller\ProdutoController::index

admin_index:
    path: /admin
    controller: App\Controller\AdminController::admin_index

admin_produto_add:
    path: /admin/produtos/add
    controller: App\Controller\AdminController::add_produto

admin_produto_edit:
    path: /admin/produtos/{id<\d+>}
    controller: App\Controller\AdminController::edit_produto

admin_produto_delete:
    path: /admin/produtos/delete/{id<\d+>}
    controller: App\Controller\AdminController::delete_produto

admin_unidade_add:
    path: /admin/unidades/add
    controller: App\Controller\AdminController::add_unidade

admin_unidade_edit:
    path: /admin/unidades/{id<\d+>}
    controller: App\Controller\AdminController::edit_unidade

admin_carrinho_edit:
    path: /admin/carrinho/{id<\d+>}
    controller: App\Controller\AdminController::edit_carrinho

admin_utilizador_edit:
    path: /admin/utilizador/{id}
    controller: App\Controller\AdminController::edit_utilizador

carrinho:
    path: /carrinho
    controller: App\Controller\CarrinhoController::carrinho

add_carrinho:
    path: /carrinho/add/{id}
    controller: App\Controller\CarrinhoController::add_carrinho

remove_carrinho:
    path: /carrinho/remove/{id}
    controller: App\Controller\CarrinhoController::remove_carrinho

grava_carrinho:
    path: /carrinho/gravar
    controller: App\Controller\CarrinhoController::grava_carrinho

cancela_carrinho:
    path: /carrinho/cancelar
    controller: App\Controller\CarrinhoController::cancela_carrinho

whereweare:
    path: /where-we-are
    controller: App\Controller\Controller::whereweare

whoweare:
    path: /who-we-are
    controller: App\Controller\Controller::whoweare

contactus:
    path: /contact-us
    controller: App\Controller\Controller::contactus

sendemail:
    path: /contact-us/send-email
    controller: App\Controller\MailerController::sendEmail

dashboard:
    path: /dashboard
    controller: App\Controller\UserController::dashboard

show_sell:
    path: /dashboard/carrinho/{id}
    controller: App\Controller\UserController::show_sell
