controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\Controller::index

login:
    path: /login
    controller: App\Controller\Controller::login

signup:
    path: /registar
    controller: App\Controller\Controller::signup

logout:
    path: /logout
    methods: GET

produtos:
    path: /produtos
    controller: App\Controller\ProdutoController::index

add_produto:
    path: /produto/add
    controller: App\Controller\ProdutoController::add_produto

admin_index:
    path: /admin
    controller: App\Controller\AdminController::admin_index

carrinho:
    path: /carrinho
    controller: App\Controller\CarrinhoController::carrinho

add_carrinho:
    path: /carrinho/add/{id}
    controller: App\Controller\CarrinhoController::add_carrinho

remove_carrinho:
    path: /carrinho/remove/{id}
    controller: App\Controller\CarrinhoController::remove_carrinho

grava_carrinho:
    path: /carrinho/gravar
    controller: App\Controller\CarrinhoController::grava_carrinho

cancela_carrinho:
    path: /carrinho/cancelar
    controller: App\Controller\CarrinhoController::cancela_carrinho

whereweare:
    path: /where-we-are
    controller: App\Controller\Controller::whereweare

whoweare:
    path: /who-we-are
    controller: App\Controller\Controller::whoweare

contactus:
    path: /contact-us
    controller: App\Controller\Controller::contactus

sendemail:
    path: /contact-us/send-email
    controller: App\Controller\MailerController::sendEmail

dashboard:
    path: /dashboard
    controller: App\Controller\UserController::dashboard

show_sell:
    path: /dashboard/carrinho/{id}
    controller: App\Controller\UserController::show_sell