<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerONNNzxs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerONNNzxs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerONNNzxs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerONNNzxs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerONNNzxs\App_KernelDevDebugContainer([
    'container.build_hash' => 'ONNNzxs',
    'container.build_id' => '8c16a1c9',
    'container.build_time' => 1640224903,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerONNNzxs');
