<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMzdETP1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMzdETP1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMzdETP1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMzdETP1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMzdETP1\App_KernelDevDebugContainer([
    'container.build_hash' => 'MzdETP1',
    'container.build_id' => '868971cd',
    'container.build_time' => 1639916308,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMzdETP1');
