<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKjlAlr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKjlAlr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXKjlAlr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXKjlAlr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXKjlAlr\App_KernelDevDebugContainer([
    'container.build_hash' => 'XKjlAlr',
    'container.build_id' => '84d7be6b',
    'container.build_time' => 1643135256,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKjlAlr');
