<?php

namespace ContainerZGhYCKE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactFormService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ContactForm' shared autowired service.
     *
     * @return \App\Form\ContactForm
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ContactForm'] = new \App\Form\ContactForm();
    }
}
