<?php

namespace ContainerZGhYCKE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrinhoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CarrinhoRepository' shared autowired service.
     *
     * @return \App\Repository\CarrinhoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CarrinhoRepository'] = new \App\Repository\CarrinhoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
