<?php

namespace ContainerZGhYCKE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Controller' shared autowired service.
     *
     * @return \App\Controller\Controller
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Controller'] = $instance = new \App\Controller\Controller();

        $instance->setContainer(($container->privates['.service_locator._13vCgV'] ?? $container->load('get_ServiceLocator_13vCgVService'))->withContext('App\\Controller\\Controller', $container));

        return $instance;
    }
}
