<?php

namespace ContainerZGhYCKE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrinhoProdutoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CarrinhoProdutoRepository' shared autowired service.
     *
     * @return \App\Repository\CarrinhoProdutoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CarrinhoProdutoRepository'] = new \App\Repository\CarrinhoProdutoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
