<?php

namespace ContainerZGhYCKE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrinhoFormService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CarrinhoForm' shared autowired service.
     *
     * @return \App\Form\CarrinhoForm
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CarrinhoForm'] = new \App\Form\CarrinhoForm();
    }
}
