<?php

namespace ContainerZGhYCKE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploaderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\FileUploader' shared autowired service.
     *
     * @return \App\Service\FileUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\FileUploader'] = new \App\Service\FileUploader((\dirname(__DIR__, 4).'/public/media/produtos'), ($container->privates['slugger'] ?? ($container->privates['slugger'] = new \Symfony\Component\String\Slugger\AsciiSlugger('pt'))));
    }
}
