<?php

namespace ContainerZGhYCKE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProdutoFormService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ProdutoForm' shared autowired service.
     *
     * @return \App\Form\ProdutoForm
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ProdutoForm'] = new \App\Form\ProdutoForm();
    }
}
