<?php

namespace ContainerZGhYCKE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnidadeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\UnidadeRepository' shared autowired service.
     *
     * @return \App\Repository\UnidadeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\UnidadeRepository'] = new \App\Repository\UnidadeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
